### PR TITLE
Feature/improve compatibility with natnet

### PR DESCRIPTION
**Pull request by yamokosk**
A follow up to #37.. This is a complete refactoring of the code base which achieves the following:

* A nearly identical copy of NaturalPoint's raw packet deserialization (see PacketClient.cpp from their SDK and compare to natnet_messages.cpp in this PR). This should provide support for all versions of NatNet through 3.0.
* A bulk of the refactor addressed code quality/maintainability:
- Added support for C++11
- Moved code around to better achieve single level of abstraction/single responsibility
* Command/data ports can now be specified in the config file instead of having to recompile a hardcoded value

I tested this code with the Flex13 system I have at work. It is using NatNet version 3.0.

Still TODO
* A lot more data is now being parsed from the NatNet packet (e.g. force plate data, skeletons). However, the data model only supports the high level concept of rigid bodies. If someone was feeling up to it, the data model needs to be expanded to include all the stuff we can get from NatNet.
* Licensing... I saw there was not a LICENSE file for the entire repo. Some files still have Clearpath's licensing/copyright blurb. I don't know if the original authors from Clearpath are still involved in maintaining this, but I feel like this disconnect needs to be addressed.

### CODE REVIEW

**Comment by tonybaltovski** [comment]
Thanks for this refactor @yamokosk!
Regarding the licence, it is BSD with University of Bonn and Clearpath Robotics.  Alex isn't maintaining this any more but I started to.  We do have a setup at Clearpath with Tracking tools which we used time to time.

**Comment by yamokosk** [comment]
Oh, I forgot to mention, this was tested on Kinetic.

**Comment by tonybaltovski** [comment]
That's fine with me.  Did you close by accident?

**Comment by yamokosk** [comment]
lol, maybe? I don't remember closing it but maybe I did. Sorry about that.

**Comment by BruceWheaton** [comment]
Thanks for doing this. We've been on Motive 2.x for a while.
Is this going to get merged into a main branch?

**Comment by tonybaltovski** [comment]
@BruceWheaton I do want to get this merged asap and do a release.

@yamokosk See above for licence and minor nit about launch file. And thanks again!

**Comment by yamokosk** [comment]
Thanks for the background on the license information. Shouldn't there be a LICENSE file that says the same thing? I don't know what the convention is for ROS packages.

I am failing to see the nit about the launch file in the discussion above. Are you referring to the `output=console` line? I did that during testing and forgot to remove. I will do that now.

**Comment by yamokosk** [comment]
Done. I also highlighted an error where I forgot to remove the boolean parameter `use_new_coordinates` from the config file example. This flag is now calculated internally once the node receives the server version.

**Comment by tonybaltovski** [comment]
Thanks @yamokosk!  The last thing is the license, according to the [ROS style guide](http://wiki.ros.org/CppStyleGuide#License_statements) there should be a license in each file.

**Comment by tonybaltovski** [comment]
Who ever added them I guess.  Some thoughts below
data_model.h: Kathrin Gräve, 01/2011 and yourself.
version.h: myself
rigid_body_publisher: alex benz and yourself.

I think that covers the licence headers.  I can be listed as maintainer.  I'll add linting and CI after this gets merged and do a release.

**Comment by yamokosk** [comment]
Ok, done. Take a look and let me know if I have goofed any copyright stuff.

**Comment by tonybaltovski** [comment]
LGTM, thanks!

**Pull request merged**
