### PR TITLE
Conversion to PoseStamped for Motive1.7+.

### PR DESCRIPTION
**Pull request by tonybaltovski**

### CODE REVIEW

**Comment by boris-il-forte** [comment]
any news about this pull request?

**Comment by codenotes** [comment]
Hi Boris...I can merge this, but I don't have mocap access and resources at moment to test this.  Are you confident in these changes?

**Comment by boris-il-forte** [comment]
yes, I am. However if you merge the pull request I can test tomorrow if works properly (but it should). Having a time stamped pose message is foundamental for robotics applications :)

**Comment by tonybaltovski** [comment]
Works for jwag (#11) and I.  @boris-il-forte, note that the stamps are from when the data reaches the ROS linux machine (see #12).

**Comment by boris-il-forte** [comment]
@tonybaltovski having a timestamp with (hopefully) low bias is for sure better than ros-bag arrival time stamp. At least, if you have more than one source of information you can try to estimate the timestamp...

**Comment by boris-il-forte** [comment]
Sorry for be too much insistent, but I would like to know if you are going to merge or not this pull request. If you merge the pull request, I'll will try as soon as I can. If you are not going to merge the pull request I'll fork this repo... but I think that this feature should be officially supported...

Sorry to bother you.

**Pull request merged**
